[package]
name = "wake-up-on-lan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
rand = "0.8"
serde_json = "1.0"
lru = "0.7"
futures = "0.3"
actix-files = "0.6.1"

# [dependencies.openssl]
# version = "0.10"
# # features = ["vendored"]

[dependencies.serde]
version = "1.0"
features = ["derive"]