name: Rust

on:
  push:
    paths:
      - '**.rs'
    branches: [ "master" ]
  pull_request:
    paths:
      - '**.rs'
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --verbose
    - name: run tests
      run: cargo test --verbose
    - name: commit
      run: |
        git config --global user.name "CI"
        git config --global user.email "ci@rust.ci"
        git add -A
        if git commit -m "ci" ; then
          git push
        fi
